// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(document).ready(function($) {
    $('*[title]').tooltip();
    $('#searchform').on('focus', 'input', function() {
      return $('#disc, #searchform').addClass('expand');
    });
    $('#searchform').on('blur', 'input', function() {
      return $('#disc, #searchform').removeClass('expand');
    });
    return $('a[href="#footer"]').on('click', function(event) {
      event.preventDefault();
      $('#secondFooter').slideToggle(800);
      return $('html, body').animate({
        scrollTop: $('body').height()
      }, 800);
    });
  });

}).call(this);
